SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [Sales].[SALES_ITEMS_1]
AS 

BEGIN

SELECT C.CUSTOMERID AS CUST_ID, C.STOREID, SP.ORDERDATE,  SP.SALESPERSONID, SP.TOTALDUE, SP.SALESORDERID, SOD.CARRIERTRACKINGNUMBER, SOD.MODIFIEDDATE
FROM [Sales].[Customer] C
JOIN [Sales].[SalesOrderHeader] SP ON C.CUSTOMERID = SP.CUSTOMERID
JOIN [Sales].[SalesOrderDetail] SOD ON SP.SALESORDERID = SOD.SALESORDERID

END;


GO
